// This .js file is auto-generated by `createCesium` from VeRoViz
// Display paths for cesium application

function displayPaths() {
    var pathNames = ['Drone', 'wedge_1', 'wedge_2']; 
    registerPaths(pathNames); 
    paths[0] = viewer.entities.add({
        parent: vehiclePolylines['Drone'],
        name: 'Objects Drone',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.786843, 43.000481, 0.000000, 
                -78.786843, 43.000481, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.ORANGE.withAlpha(0.800000)
            })
        }
    });
    paths[1] = viewer.entities.add({
        parent: vehiclePolylines['Drone'],
        name: 'Objects Drone',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.786843, 43.000481, 25.000000, 
                -78.786843, 43.000481, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.ORANGE.withAlpha(0.800000)
            })
        }
    });
    paths[2] = viewer.entities.add({
        parent: vehiclePolylines['Drone'],
        name: 'Objects Drone',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.786843, 43.000481, 25.000000, 
                -78.787529, 43.004067, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.ORANGE.withAlpha(0.800000)
            })
        }
    });
    paths[3] = viewer.entities.add({
        parent: vehiclePolylines['Drone'],
        name: 'Objects Drone',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.787529, 43.004067, 25.000000, 
                -78.789489, 42.994356, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.ORANGE.withAlpha(0.800000)
            })
        }
    });
    paths[4] = viewer.entities.add({
        parent: vehiclePolylines['Drone'],
        name: 'Objects Drone',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.789489, 42.994356, 25.000000, 
                -78.786843, 43.000481, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.ORANGE.withAlpha(0.800000)
            })
        }
    });
    paths[5] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.787529, 43.004067, 25.000000, 
                -78.779469, 43.000366, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[6] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.779469, 43.000366, 0.000000, 
                -78.787529, 43.004067, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[7] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.787529, 43.004067, 25.000000, 
                -78.792515, 42.998863, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[8] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.792515, 42.998863, 0.000000, 
                -78.787529, 43.004067, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[9] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.787529, 43.004067, 25.000000, 
                -78.779476, 43.000010, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[10] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.779476, 43.000010, 0.000000, 
                -78.787529, 43.004067, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[11] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.787529, 43.004067, 25.000000, 
                -78.778503, 42.997827, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[12] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.778503, 42.997827, 0.000000, 
                -78.787529, 43.004067, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[13] = viewer.entities.add({
        parent: vehiclePolylines['wedge_1'],
        name: 'Objects wedge_1',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.787529, 43.004067, 25.000000, 
                -78.777730, 42.997889, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.RED.withAlpha(0.800000)
            })
        }
    });
    paths[14] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.789489, 42.994356, 25.000000, 
                -78.783789, 43.003983, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[15] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.783789, 43.003983, 0.000000, 
                -78.789489, 42.994356, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[16] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.789489, 42.994356, 25.000000, 
                -78.796270, 43.000622, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[17] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.796270, 43.000622, 0.000000, 
                -78.789489, 42.994356, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[18] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.789489, 42.994356, 25.000000, 
                -78.791878, 42.997895, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[19] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.791878, 42.997895, 0.000000, 
                -78.789489, 42.994356, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[20] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.789489, 42.994356, 25.000000, 
                -78.791900, 42.997565, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[21] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.791900, 42.997565, 0.000000, 
                -78.789489, 42.994356, 25.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
    paths[22] = viewer.entities.add({
        parent: vehiclePolylines['wedge_2'],
        name: 'Objects wedge_2',
        description: 'None',
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArrayHeights([
                -78.789489, 42.994356, 25.000000, 
                -78.787508, 42.999654, 0.000000            
            ]),
            width: 3, 
            material: new Cesium.PolylineDashMaterialProperty({
                dashLength: 0.000000,
                color: Cesium.Color.GREEN.withAlpha(0.800000)
            })
        }
    });
}